apiVersion: apps/v1
kind: Deployment
metadata:
  name: m-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m-app
  template:
    metadata:
      labels:
        app: m-app
    spec:
      containers:
        - name: m-app-container
          image: 127.0.0.1:8082/node:latest
          ports:
            - containerPort: 8088
      imagePullSecrets:
        - name: m-sec


---

apiVersion: v1
kind: Service
metadata:
  name: m-app-service
spec:
  selector:
    app: m-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 80
    nodePort: 31111
        
